https://www.kaggle.com/Cornell-University/arxiv

In [1]:
import pickle as pkl
import networkx as nx
import numpy as np
import sys
import scipy.sparse as sp
import torch
import pandas as pd
import os
from numpy import dot

In [2]:
data = pd.read_csv('arx_condmat_coa_adj.csv'); data.head()

,0,1,2,3,4,5,6,7,8,9,...,9990,9991,9992,9993,9994,9995,9996,9997,9998,9999
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
dv = data.values
np.fill_diagonal(dv, 0)

In [4]:
np.count_nonzero(dv)

40344

In [5]:
G = nx.from_numpy_matrix(dv)
adj = nx.adjacency_matrix(G)

### Feature

In [14]:
feat = pd.read_csv('arx_coa_condmat_feat.csv'); feat.head()

,aa,aao,ab,aba,abaqus,abc,abelian,abilities,ability,ablation,...,zrnbr,zrnbtivhf,zrnisn,zrsis,zrsise,zt,zts,zwanzig,zx,labels_
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,cond-mat.str-el
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,cond-mat.mes-hall
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,cond-mat.stat-mech
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,cond-mat.soft
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,cond-mat.mtrl-sci

In [23]:
featv = feat.iloc[:,:-1].values
feat_sp = sp.csr_matrix(featv).astype(float)

In [24]:
# with open('data/arx.feature', 'wb') as f:
#     pkl.dump(feat_sp, f)

### Labels

In [21]:
labels = feat.iloc[:, -1]
labels = labels.values; labels

array(['cond-mat.str-el', 'cond-mat.mes-hall', 'cond-mat.stat-mech', ...,
       'cond-mat.mtrl-sci', 'cond-mat.stat-mech', 'cond-mat.mes-hall'],
      dtype=object)

In [22]:
# with open('data/arx.labels', 'wb') as f:
#     pkl.dump(labels, f)